from .accesscontrolalloworigin import AccessControlAllowOrigin
from .accesscontrolalloworigindirective import AccessControlAllowOriginDirective

__all__ = ['AccessControlAllowOrigin','AccessControlAllowOriginDirective']
